buildConfiguration:
  buildCommand: npm run build:local
  installDependenciesStep:
    command: npm install
    requiredFiles:
      - package.json
      - package-lock.json
      - .npmrc
livePreviewConfiguration:
  setupCommand: ":"
siteStream:
  id: site-entity
  source: knowledgeGraph
  fields:
    - name
    - c_deskHeader
    - c_deskFooter
    - c_mobHeader
    - c_mobFooter
    - primaryPhoto
    - c_templateBBanner
    - c_brandLogo
  localization:
    locales:
      - en
    primary: false
  entityId: "4343719759278830624"
